spring:
  config:
    import:

  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/there?serverTimezone=Asia/Seoul
    username:
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
#    database-platform: MYSQL
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
springdoc:
  swagger-ui:
    path: /api-doc.html