spring:
  config:
    import:
      - classpath:awsS3.yml
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:h2:mem:test;MODE=MYSQL
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
    database-platform: H2
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

springdoc:
  swagger-ui:
    path: /api-doc.html