spring:
  config:
    import:

  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/there?serverTimezone=Asia/Seoul
    username:
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
    #    database-platform: MYSQL
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

springdoc:
  swagger-ui:
    path: /api-doc.html